package com.twitter.entities.tweet;

import com.twitter.entities.tweet.content.ImageContent;
import com.twitter.entities.tweet.content.TextContent;
import com.twitter.entities.user.MiniUser;

import java.io.Serializable;
import java.time.LocalDateTime;

public abstract class BaseTweet implements Serializable
{
    // this is automatically generated by the database
    private int id;
    private MiniUser owner;
    private final TextContent textContent;
    private final ImageContent imageContent;
    private int likeCount;
    private int retweetCount;
    private int quoteCount;
    private LocalDateTime tweetDate;

    public BaseTweet(TextContent textContent, ImageContent imageContent)
    {
        id = -1;
        this.textContent = textContent;
        this.imageContent = imageContent;
        likeCount = 0;
        retweetCount = 0;
        quoteCount = 0;
        tweetDate = LocalDateTime.now();
    }

    public BaseTweet(TextContent textContent)
    {
        this(textContent, null);
    }

    public BaseTweet(ImageContent imageContent)
    {
        this(null, imageContent);
    }

    public MiniUser getOwner()
    {
        return owner;
    }

    public void setOwner(MiniUser owner)
    {
        this.owner = owner;
    }

    public TextContent getTextContent()
    {
        return textContent;
    }

    public ImageContent getImageContent()
    {
        return imageContent;
    }

    public int getId()
    {
        return id;
    }

    public void setId(int id)
    {
        this.id = id;
    }

    public int getLikeCount()
    {
        return likeCount;
    }

    public void setLikeCount(int likeCount)
    {
        this.likeCount = likeCount;
    }

    public int getRetweetCount()
    {
        return retweetCount;
    }

    public void setRetweetCount(int retweetCount)
    {
        this.retweetCount = retweetCount;
    }

    public int getQuoteCount()
    {
        return quoteCount;
    }

    public void setQuoteCount(int quoteCount)
    {
        this.quoteCount = quoteCount;
    }

    public LocalDateTime getTweetDate()
    {
        return tweetDate;
    }

    public void setTweetDate(LocalDateTime tweetDate)
    {
        this.tweetDate = tweetDate;
    }
}
