package com.twitter.entities.tweet;

import com.twitter.entities.exception.UnknownException;
import com.twitter.entities.user.MiniUser;

import java.time.LocalDateTime;

public abstract class BaseTweet
{
    // this is automatically generated by the database
    private final long id;
    private final LocalDateTime date;
    private final MiniUser owner;

    public BaseTweet(int id, LocalDateTime date, MiniUser owner)
    {
        this.id = id;
        this.date = date;
        this.owner = owner;
    }

    public BaseTweet(MiniUser owner)
    {
        this(-1, LocalDateTime.now(), owner);
    }

    public long getId()
    {
        return id;
    }

    // this is the date the tweet was created
    public LocalDateTime getDate()
    {
        return date;
    }

    public Tweet toTweet() throws UnknownException
    {
        if(this instanceof Tweet)
            return (Tweet) this;
        else if(this instanceof Retweet)
            return ((Retweet) this).getTweet();
        else
            throw new UnknownException("Unknown tweet type");
    }

    public MiniUser getOwner()
    {
        return owner;
    }
}
