package com.twitter.entities.tweet;

import com.twitter.entities.user.MiniUser;

import java.io.Serializable;
import java.time.LocalDateTime;

public class Retweet implements Serializable
{
    // this is automatically generated by the database
    private int id;
    private final Tweet tweet;
    private final MiniUser retweetedBy;
    private final LocalDateTime date;

    public Retweet(Tweet tweet, MiniUser retweetedBy)
    {
        this.id = -1;
        this.tweet = tweet;
        this.date = LocalDateTime.now();
        this.retweetedBy = retweetedBy;
    }

    public Retweet(Tweet tweet, MiniUser retweetedBy, LocalDateTime date)
    {
        this.id = -1;
        this.tweet = tweet;
        this.date = date;
        this.retweetedBy = retweetedBy;
    }

    public int getId()
    {
        return id;
    }

    public void setId(int id)
    {
        this.id = id;
    }

    public Tweet getTweet()
    {
        return tweet;
    }

    public MiniUser getRetweetedBy()
    {
        return retweetedBy;
    }

    public LocalDateTime getDate()
    {
        return date;
    }
}
