package com.twitter.entities.tweet;

import com.twitter.entities.tweet.content.ImageContent;
import com.twitter.entities.tweet.content.TextContent;
import com.twitter.entities.user.MiniUser;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.ArrayList;

public class Tweet implements Serializable
{
    // this is automatically generated by the database
    private int id;
    private final MiniUser owner;
    private final TextContent textContent;
    private final ImageContent imageContent;
    private int likeCount;
    private int retweetCount;
    private int quoteCount;
    private final LocalDateTime tweetDate;
    private final ArrayList<Retweet> retweets;
    private final ArrayList<Quote> quotes;
    private final ArrayList<Reply> replies;

    public Tweet(MiniUser owner, TextContent textContent, ImageContent imageContent)
    {
        id = -1;
        this.owner = owner;
        this.textContent = textContent;
        this.imageContent = imageContent;
        likeCount = 0;
        retweetCount = 0;
        quoteCount = 0;
        tweetDate = LocalDateTime.now();
        retweets = new ArrayList<>();
        quotes = new ArrayList<>();
        replies = new ArrayList<>();
    }

    public Tweet(MiniUser owner, TextContent textContent, ImageContent imageContent, LocalDateTime tweetDate)
    {
        id = -1;
        this.owner = owner;
        this.textContent = textContent;
        this.imageContent = imageContent;
        likeCount = 0;
        retweetCount = 0;
        quoteCount = 0;
        this.tweetDate = tweetDate;
        retweets = new ArrayList<>();
        quotes = new ArrayList<>();
        replies = new ArrayList<>();
    }

    public MiniUser getOwner()
    {
        return owner;
    }

    public TextContent getTextContent()
    {
        return textContent;
    }

    public ImageContent getImageContent()
    {
        return imageContent;
    }

    public int getId()
    {
        return id;
    }

    public void setId(int id)
    {
        this.id = id;
    }

    public int getLikeCount()
    {
        return likeCount;
    }

    public void setLikeCount(int likeCount)
    {
        this.likeCount = likeCount;
    }

    public int getRetweetCount()
    {
        return retweetCount;
    }

    public void setRetweetCount(int retweetCount)
    {
        this.retweetCount = retweetCount;
    }

    public int getQuoteCount()
    {
        return quoteCount;
    }

    public void setQuoteCount(int quoteCount)
    {
        this.quoteCount = quoteCount;
    }

    public LocalDateTime getTweetDate()
    {
        return tweetDate;
    }

    public ArrayList<Retweet> getRetweets()
    {
        return retweets;
    }

    public ArrayList<Quote> getQuotes()
    {
        return quotes;
    }

    public ArrayList<Reply> getReplies()
    {
        return replies;
    }

    public Retweet getRetweet(int retweetId)
    {
        for (Retweet retweet : retweets)
            if (retweet.getId() == retweetId)
                return retweet;
        return null;
    }

    public Quote getQuote(int quoteId)
    {
        for (Quote quote : quotes)
            if (quote.getId() == quoteId)
                return quote;
        return null;
    }

    public Reply getReply(int replyId)
    {
        for (Reply reply : replies)
            if (reply.getId() == replyId)
                return reply;
        return null;
    }
}
